export const plainApiRegionDomainMap: Record<string, string> = {
    as: "https://as-apia.coolkit.cc",
    cn: "https://cn-apia.coolkit.cn",
    us: "https://us-apia.coolkit.cc",
    eu: "https://eu-apia.coolkit.cc"
}



export const countries: Array<{ name: string; code: string }> = [
    { name: '中国', code: '+86' },
    { name: '美国', code: '+1' },
    { name: '日本', code: '+81' },
    { name: '韩国', code: '+82' },
    { name: '英国', code: '+44' },
    { name: '法国', code: '+33' },
    { name: '德国', code: '+49' },
    { name: '意大利', code: '+39' },
    { name: '俄罗斯', code: '+7' },
    { name: '印度', code: '+91' },
    { name: '巴西', code: '+55' },
    { name: '加拿大', code: '+1' },
    { name: '澳大利亚', code: '+61' },
    { name: '新加坡', code: '+65' },
    { name: '马来西亚', code: '+60' },
    { name: '泰国', code: '+66' },
    { name: '越南', code: '+84' },
    { name: '印度尼西亚', code: '+62' },
    { name: '菲律宾', code: '+63' },
    { name: '墨西哥', code: '+52' },
    { name: '西班牙', code: '+34' },
    { name: '荷兰', code: '+31' },
    { name: '瑞士', code: '+41' },
    { name: '瑞典', code: '+46' },
    { name: '挪威', code: '+47' },
    { name: '丹麦', code: '+45' },
    { name: '芬兰', code: '+358' },
    { name: '波兰', code: '+48' },
    { name: '土耳其', code: '+90' },
    { name: '阿联酋', code: '+971' },
    { name: '沙特阿拉伯', code: '+966' },
    { name: '南非', code: '+27' },
    { name: '埃及', code: '+20' },
    { name: '尼日利亚', code: '+234' },
    { name: '阿根廷', code: '+54' },
    { name: '智利', code: '+56' },
    { name: '哥伦比亚', code: '+57' },
    { name: '秘鲁', code: '+51' },
    { name: '新西兰', code: '+64' },
    { name: '中国香港', code: '+852' },
    { name: '中国台湾', code: '+886' },
    { name: '中国澳门', code: '+853' },
    { name: '巴基斯坦', code: '+92' },
    { name: '孟加拉国', code: '+880' },
    { name: '葡萄牙', code: '+351' },
    { name: '比利时', code: '+32' },
    { name: '奥地利', code: '+43' },
    { name: '爱尔兰', code: '+353' },
    { name: '捷克', code: '+420' },
    { name: '罗马尼亚', code: '+40' },
    { name: '希腊', code: '+30' },
    { name: '乌克兰', code: '+380' },
    { name: '以色列', code: '+972' },
    { name: '伊拉克', code: '+964' },
    { name: '伊朗', code: '+98' },
]
